---
- name: Deploy Next.js project to Kubernetes
  hosts: localhost
  gather_facts: no
  vars:
    k8s_namespace: "default"
    docker_image: "{{ docker_image }}"

  tasks:
    - name: Create Kubernetes namespace if not exists
      kubernetes.core.k8s_namespace:
        name: "default"
        state: present

    - name: Deploy the Next.js Docker container
      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nextjs-deployment
            namespace: "default"
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: nextjs
            template:
              metadata:
                labels:
                  app: nextjs
              spec:
                containers:
                - name: nextjs
                  image: "{{ docker_image }}"
                  ports:
                  - containerPort: 3000
    - name: Expose Next.js service
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nextjs-service
            namespace: "default"
          spec:
            selector:
              app: nextjs
            ports:
              - protocol: TCP
                port: 80
                targetPort: 3000
            type: LoadBalancer
